services:
  - type: web
    name: Sid's-Blog-App
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Blog.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Blog.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
    databaseName: blog
    user: blog_user
